package view;

import exceptions.NivelDifException;
import exceptions.NomeException;
import controller.LancheController;
import model.Lanche;
import javax.swing.JOptionPane;


public class FormLanche extends javax.swing.JFrame {
    private static FormLanche formLanche;
      
    private FormLanche() {
        initComponents();
        
    }

    public static FormLanche getFormLanche(){
        if(formLanche == null){
            formLanche = new FormLanche();
        }
        return formLanche;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelTitulo = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        txfieldNome = new javax.swing.JTextField();
        labelTempPrep = new javax.swing.JLabel();
        txfieldTempPrep = new javax.swing.JTextField();
        labelNivDif = new javax.swing.JLabel();
        txfieldNivDif = new javax.swing.JTextField();
        labelKcal = new javax.swing.JLabel();
        txfieldKcal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btAdicionarLanche = new javax.swing.JButton();
        labelTipoLanche = new javax.swing.JLabel();
        labelTemperatura = new javax.swing.JLabel();
        txfieldTipoLanche = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        txfieldTemperatura = new javax.swing.JTextField();
        labelPorcoes = new javax.swing.JLabel();
        txfieldPorcoes = new javax.swing.JTextField();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        labelTitulo.setText("Adicionar Lanche");

        labelNome.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelNome.setText("Nome:");

        txfieldNome.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txfieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfieldNomeActionPerformed(evt);
            }
        });

        labelTempPrep.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelTempPrep.setText("Tempo de preparo (min):");

        txfieldTempPrep.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        labelNivDif.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelNivDif.setText("Nível de Dificuldade (1 a 5):");

        txfieldNivDif.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        labelKcal.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelKcal.setText("Valor Kcal:");

        txfieldKcal.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txfieldKcal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txfieldKcal.setMinimumSize(new java.awt.Dimension(90, 24));

        btAdicionarLanche.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btAdicionarLanche.setText("Adicionar Lanche");
        btAdicionarLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarLancheActionPerformed(evt);
            }
        });

        labelTipoLanche.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelTipoLanche.setText("Tipo do lanche:");

        labelTemperatura.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelTemperatura.setText("Temperatura:");

        txfieldTipoLanche.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txfieldTipoLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfieldTipoLancheActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setBackground(new java.awt.Color(242, 242, 242));
        btSair.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        txfieldTemperatura.setPreferredSize(new java.awt.Dimension(80, 23));
        txfieldTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfieldTemperaturaActionPerformed(evt);
            }
        });

        labelPorcoes.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelPorcoes.setText("Porções:");

        txfieldPorcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfieldPorcoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAdicionarLanche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelNivDif)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfieldNivDif, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelTipoLanche)
                                    .addGap(18, 18, 18)
                                    .addComponent(txfieldTipoLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelPorcoes)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfieldPorcoes))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelKcal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfieldKcal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfieldTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(157, 157, 157))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTempPrep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfieldTempPrep, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(txfieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTempPrep)
                    .addComponent(txfieldTempPrep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfieldNivDif, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNivDif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfieldKcal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKcal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPorcoes)
                    .addComponent(txfieldPorcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfieldTipoLanche, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(labelTipoLanche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTemperatura)
                    .addComponent(txfieldTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionarLanche)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfieldNomeActionPerformed

    private void btAdicionarLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarLancheActionPerformed
        cadastrarLanche();
    }//GEN-LAST:event_btAdicionarLancheActionPerformed

    private void txfieldTipoLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfieldTipoLancheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfieldTipoLancheActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    }//GEN-LAST:event_formWindowActivated

    private void txfieldTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfieldTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfieldTemperaturaActionPerformed

    private void txfieldPorcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfieldPorcoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfieldPorcoesActionPerformed

        
    private void cadastrarLanche() {
        Lanche lanche = new Lanche();

        try {
            lanche.setNome(txfieldNome.getText());
        } catch (NomeException ne) {
            JOptionPane.showMessageDialog(this, "Nome inválido! O nome deve ter pelo menos 3 caracteres.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNome.setText("");
            txfieldNome.requestFocus();
            return;
        }  

        try {
            lanche.setNivelDific(Integer.parseInt(txfieldNivDif.getText()));
        } catch (NivelDifException nde) {
            JOptionPane.showMessageDialog(this, "Nível de dificuldade deve estar entre 1 e 5.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNivDif.setText("");
            txfieldNivDif.requestFocus();
            return;
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Entrada inválida! Digite um número inteiro.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNivDif.setText("");
            txfieldNivDif.requestFocus();
            return;
        }

        try {
            lanche.setValorKcal(Integer.parseInt(txfieldKcal.getText()));
            lanche.setTempPreparo(Integer.parseInt(txfieldTempPrep.getText()));
            lanche.setPorcoes(Integer.parseInt(txfieldPorcoes.getText()));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Erro: Certifique-se de preencher os campos corretamente com números!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        lanche.setTipoLanche(txfieldTipoLanche.getText());
        lanche.setTemperatura(txfieldTemperatura.getText());

        LancheController ct = new LancheController();
        int id = ct.cadastrar(lanche);
        
        if (id <= 0){
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar lanche no Banco de Dados", "ERRO", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        lanche.setId(id);
        
        FormIngrediente formIngrediente = FormIngrediente.getFormIngrediente();
        formIngrediente.setReceitaAtual(lanche);  
        formIngrediente.limparTabelaIngredientes(); 
        FormIngrediente.getFormIngrediente().setVisible(true);
        
        JOptionPane.showMessageDialog(this, "Lanche cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        limpar();
        this.dispose();
    }

    public void limpar(){
        txfieldKcal.setText("");
        txfieldNivDif.setText("");
        txfieldNome.setText("");
        txfieldTempPrep.setText("");
        txfieldTipoLanche.setText("");
        txfieldTemperatura.setText("");
        txfieldPorcoes.setText("");
        txfieldNome.requestFocus();
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Saida", JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLanche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarLanche;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelKcal;
    private javax.swing.JLabel labelNivDif;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPorcoes;
    private javax.swing.JLabel labelTempPrep;
    private javax.swing.JLabel labelTemperatura;
    private javax.swing.JLabel labelTipoLanche;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField txfieldKcal;
    private javax.swing.JTextField txfieldNivDif;
    private javax.swing.JTextField txfieldNome;
    private javax.swing.JTextField txfieldPorcoes;
    private javax.swing.JTextField txfieldTempPrep;
    private javax.swing.JTextField txfieldTemperatura;
    private javax.swing.JTextField txfieldTipoLanche;
    // End of variables declaration//GEN-END:variables
}
