package view;

import controller.ReceitaController;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class FormExcluir extends javax.swing.JFrame {
    private static FormExcluir formExcluir;
    private ReceitaController rc = new ReceitaController();
    private DefaultListModel<String> listaModelo;

    private FormExcluir() {
        initComponents();
        listaModelo = new DefaultListModel<>();
        listReceitasCad.setModel(listaModelo);
        carregarListaReceitas();
    }

    public static FormExcluir getFormExcluir(){
        if(formExcluir == null){
           formExcluir = new FormExcluir();
        }
        return formExcluir;
    }


/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelExcluir = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listReceitasCad = new javax.swing.JList<>();
        labelDesejaExcluir = new javax.swing.JLabel();
        txtfieldDesejaExcluir = new javax.swing.JTextField();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        labelExcluir.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        labelExcluir.setText("Excluir Receitas");

        listReceitasCad.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listReceitasCad);

        labelDesejaExcluir.setText("Qual receita deseja excluir?");

        txtfieldDesejaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldDesejaExcluirActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelDesejaExcluir)
                        .addComponent(jScrollPane1)
                        .addComponent(txtfieldDesejaExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(labelExcluir)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelExcluir)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(labelDesejaExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfieldDesejaExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir)
                    .addComponent(btSair))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfieldDesejaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldDesejaExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldDesejaExcluirActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirReceita();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void carregarListaReceitas() {
        List<String> nomesReceitas = rc.listarNomesReceitas();
        listaModelo.clear();

        if (nomesReceitas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma receita cadastrada.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            for (String nome : nomesReceitas) {
                listaModelo.addElement(nome);
            }
        }
    }

    private void excluirReceita() {
        String nomeExcluir = txtfieldDesejaExcluir.getText().trim();

        if (nomeExcluir.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um nome para excluir!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacao = JOptionPane.showConfirmDialog(this,
            "Tem certeza que deseja excluir a receita \"" + nomeExcluir + "\"?",
            "Confirmação", JOptionPane.YES_NO_OPTION);

        if (confirmacao != JOptionPane.YES_OPTION) return;
        
        ReceitaController ct = new ReceitaController();
        boolean sucesso = ct.excluirReceitaPorNome(nomeExcluir);
                
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Receita excluída com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            carregarListaReceitas(); 
        } else {
            JOptionPane.showMessageDialog(this, "Receita não encontrada!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

     public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Saida", JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormExcluir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDesejaExcluir;
    private javax.swing.JLabel labelExcluir;
    private javax.swing.JList<String> listReceitasCad;
    private javax.swing.JTextField txtfieldDesejaExcluir;
    // End of variables declaration//GEN-END:variables
}
