package view;

//Netbeans IDE23
//Isadora Costa Baía - RA2614685
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import model.Sobremesa;
import javax.swing.JOptionPane;

/**
 *
 * @author isadorabaia
 */
public class FormSobremesa extends javax.swing.JFrame {
    private Sobremesa sobremesa;
    private static FormSobremesa cadSobremesa;
        
    
    /**
     * Creates new form CadLanche
     */
    private FormSobremesa() {
        initComponents();
    }

    //método singleton
    public static FormSobremesa getCadSobremesa(){
        if(cadSobremesa == null){
            cadSobremesa = new FormSobremesa();
        }
        return cadSobremesa;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelTitulo = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        txfieldNome = new javax.swing.JTextField();
        labelTempPrep = new javax.swing.JLabel();
        txfieldTempPrep = new javax.swing.JTextField();
        labelNivDif = new javax.swing.JLabel();
        txfieldNivDif = new javax.swing.JTextField();
        labelKcal = new javax.swing.JLabel();
        txfieldKcal = new javax.swing.JTextField();
        btAdicionarSobremesa = new javax.swing.JButton();
        labelNivelDoce = new javax.swing.JLabel();
        labelTempIdeal = new javax.swing.JLabel();
        txfieldNivelDoce = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        txfieldTempIdeal = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        labelTitulo.setText("Adicionar Sobremesa");

        labelNome.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelNome.setText("Nome:");

        txfieldNome.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txfieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfieldNomeActionPerformed(evt);
            }
        });

        labelTempPrep.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelTempPrep.setText("Tempo de preparo (min):");

        txfieldTempPrep.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        labelNivDif.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelNivDif.setText("Nível de Dificuldade (1 a 5):");

        labelKcal.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelKcal.setText("Valor Kcal:");

        txfieldKcal.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        btAdicionarSobremesa.setText("Adicionar Sobremesa");
        btAdicionarSobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarSobremesaActionPerformed(evt);
            }
        });

        labelNivelDoce.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelNivelDoce.setText("Nível de Doce (1 a 5):");

        labelTempIdeal.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelTempIdeal.setText("Temperatura Ideal:");

        txfieldNivelDoce.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txfieldNivelDoce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfieldNivelDoceActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTempIdeal)
                                    .addComponent(labelNivelDoce))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfieldNivelDoce)
                                    .addComponent(txfieldTempIdeal)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelKcal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfieldKcal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNivDif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfieldNivDif))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTempPrep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfieldTempPrep, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAdicionarSobremesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSair)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(txfieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTempPrep)
                    .addComponent(txfieldTempPrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNivDif)
                    .addComponent(txfieldNivDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKcal)
                    .addComponent(txfieldKcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNivelDoce)
                    .addComponent(txfieldNivelDoce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTempIdeal)
                    .addComponent(txfieldTempIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionarSobremesa)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfieldNomeActionPerformed

    private void btAdicionarSobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarSobremesaActionPerformed
        cadastrarSobremesa();
    }//GEN-LAST:event_btAdicionarSobremesaActionPerformed

    private void txfieldNivelDoceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfieldNivelDoceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfieldNivelDoceActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed
    
    private void cadastrarSobremesa() {
        Sobremesa sobremesa = new Sobremesa();

        try {
            sobremesa.setNome(txfieldNome.getText());
        } catch (NomeException ne) {
            JOptionPane.showMessageDialog(this, "Nome inválido! O nome deve ter pelo menos 3 caracteres.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNome.setText("");
            txfieldNome.requestFocus();
            return;
        }  

        try {
            sobremesa.setNivelDific(Integer.parseInt(txfieldNivDif.getText()));
        } catch (NivelDifException nde) {
            JOptionPane.showMessageDialog(this, "Nível de dificuldade deve estar entre 1 e 5.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNivDif.setText("");
            txfieldNivDif.requestFocus();
            return;
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Entrada inválida! Digite um número inteiro.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNivDif.setText("");
            txfieldNivDif.requestFocus();
            return;
        }

        try {
            sobremesa.setValorKcal(Integer.parseInt(txfieldKcal.getText()));
            sobremesa.setTempPreparo(Integer.parseInt(txfieldTempPrep.getText()));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Erro: Certifique-se de preencher os campos corretamente com números!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            sobremesa.setNivelDoce(Integer.parseInt(txfieldNivelDoce.getText()));        
        } catch (NivelDifException nde) {
            JOptionPane.showMessageDialog(this, "Nível de doce deve estar entre 1 e 5.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNivelDoce.setText("");
            txfieldNivelDoce.requestFocus();
            return;
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Entrada inválida! Digite um número inteiro.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNivelDoce.setText("");
            txfieldNivelDoce.requestFocus();
            return;
        }
        
        sobremesa.setTempIdeal(txfieldTempIdeal.getText());

        FormIngrediente formIngrediente = FormIngrediente.getCadIngrediente();
        formIngrediente.setReceitaAtual(sobremesa);  

        FormIngrediente.getCadIngrediente().setVisible(true);
          
        BdReceitas.getBdReceitas().adicionarReceita(sobremesa);

        JOptionPane.showMessageDialog(this, "Sobremesa cadastrada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        limpar();
        this.dispose();
    }
      
    public void limpar(){
        txfieldKcal.setText("");
        txfieldNivDif.setText("");
        txfieldNome.setText("");
        txfieldTempPrep.setText("");
        txfieldNivelDoce.setText("");
        txfieldTempIdeal.setText("");
        txfieldNome.requestFocus();
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Saida", JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSobremesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSobremesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSobremesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSobremesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSobremesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarSobremesa;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelKcal;
    private javax.swing.JLabel labelNivDif;
    private javax.swing.JLabel labelNivelDoce;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTempIdeal;
    private javax.swing.JLabel labelTempPrep;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField txfieldKcal;
    private javax.swing.JTextField txfieldNivDif;
    private javax.swing.JTextField txfieldNivelDoce;
    private javax.swing.JTextField txfieldNome;
    private javax.swing.JTextField txfieldTempIdeal;
    private javax.swing.JTextField txfieldTempPrep;
    // End of variables declaration//GEN-END:variables
}
