package view;

//Netbeans IDE23
//Isadora Costa Baía - RA2614685
import model.Ingrediente;
import model.Receita;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author isadorabaia
 */
public class FormConsultar extends javax.swing.JFrame {
    private static FormConsultar formConsulta;
    private BdReceitas gerReceitas;
    private DefaultListModel<String> listaModelo;

    /**
     * Creates new form FormConsulta
     */
    private FormConsultar() {
        initComponents();
        gerReceitas = BdReceitas.getBdReceitas();
        listaModelo = new DefaultListModel<>();
        jListReceitas.setModel(listaModelo);
        carregarListaReceitas();
    }

    //método Singleton
    public static FormConsultar getFormConsulta() {
        if (formConsulta == null || !formConsulta.isDisplayable()) {
            formConsulta = new FormConsultar();
        }
        return formConsulta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelConsulta = new javax.swing.JLabel();
        labelDesejaCons = new javax.swing.JLabel();
        txtfieldDesejaCons = new javax.swing.JTextField();
        btConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListReceitas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableReceita = new javax.swing.JTable();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelConsulta.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        labelConsulta.setText("Consulta de Receitas");

        labelDesejaCons.setText("Qual receita deseja consultar?");

        txtfieldDesejaCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldDesejaConsActionPerformed(evt);
            }
        });

        btConsultar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListReceitas);

        jTableReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableReceita);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSair)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btConsultar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelDesejaCons)
                                .addComponent(txtfieldDesejaCons, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(labelConsulta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelDesejaCons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfieldDesejaCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultar)
                    .addComponent(btSair))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfieldDesejaConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldDesejaConsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldDesejaConsActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultarReceita();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed
    
    private void carregarListaReceitas() {
        ArrayList<String> nomesReceitas = gerReceitas.listarNomesReceitas();
        listaModelo.clear();

        if (nomesReceitas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma receita cadastrada.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            for (String nome : nomesReceitas) {
                listaModelo.addElement(nome);
            }
        }
    }

    private void consultarReceita() {
        String nomeConsulta = txtfieldDesejaCons.getText().trim();

        if (nomeConsulta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um nome para a consulta!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Receita receitaEncontrada = gerReceitas.encontrarReceita(nomeConsulta);

        if (receitaEncontrada != null) {
            exibirDetalhesNaTabela(receitaEncontrada);
        } else {
            JOptionPane.showMessageDialog(this, "Receita não encontrada!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exibirDetalhesNaTabela(Receita receita) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"Campo", "Valor"});

        modelo.addRow(new Object[]{"Nome", receita.getNome()});
        modelo.addRow(new Object[]{"Tempo de Preparo", receita.getTempPreparo() + " minutos"});
        modelo.addRow(new Object[]{"Nível de Dificuldade", receita.getNivelDific()});
        modelo.addRow(new Object[]{"Calorias", receita.getValorKcal()});

        if (!receita.getIngredientes().isEmpty()) {
            for (Ingrediente ing : receita.getIngredientes()) {
                modelo.addRow(new Object[]{"Ingrediente", ing.getNome() + ": " + ing.getQuantidade() + " " + ing.getUnidMedida()});
            }
        } else {
            modelo.addRow(new Object[]{"Ingredientes", "Nenhum cadastrado"});
        }

        jTableReceita.setModel(modelo); 
    }

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Saida", JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btSair;
    private javax.swing.JList<String> jListReceitas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableReceita;
    private javax.swing.JLabel labelConsulta;
    private javax.swing.JLabel labelDesejaCons;
    private javax.swing.JTextField txtfieldDesejaCons;
    // End of variables declaration//GEN-END:variables
}
