package view;

import controller.ReceitaController;
import exceptions.NivelDifException;
import exceptions.NomeException;
import model.Ingrediente;
import model.Receita;
import model.Lanche;
import model.Refeicao;
import model.Sobremesa;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormConsultar extends javax.swing.JFrame {
    private static FormConsultar formConsulta;
    private ReceitaController rc = new ReceitaController();
    private DefaultListModel<String> listaModelo;

    private FormConsultar() {
        initComponents();
        listaModelo = new DefaultListModel<>();
        jListReceitas.setModel(listaModelo);
        carregarListaReceitas();
    }

    public static FormConsultar getFormConsulta() {
        if (formConsulta == null || !formConsulta.isDisplayable()) {
            formConsulta = new FormConsultar();
        }
        return formConsulta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelConsulta = new javax.swing.JLabel();
        labelDesejaCons = new javax.swing.JLabel();
        txtfieldDesejaCons = new javax.swing.JTextField();
        btConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListReceitas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableReceita = new javax.swing.JTable();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        labelConsulta.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        labelConsulta.setText("Consulta de Receitas");

        labelDesejaCons.setText("Qual receita deseja consultar?");

        txtfieldDesejaCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldDesejaConsActionPerformed(evt);
            }
        });

        btConsultar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListReceitas);

        jTableReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableReceita);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(labelConsulta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btConsultar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btSair))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelDesejaCons)
                                            .addComponent(txtfieldDesejaCons, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(16, 16, 16))))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelConsulta)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelDesejaCons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfieldDesejaCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultar)
                    .addComponent(btSair))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfieldDesejaConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldDesejaConsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldDesejaConsActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultarReceita();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed
    
    private void carregarListaReceitas() {
        List<String> nomesReceitas = rc.listarNomesReceitas();
        listaModelo.clear();

        if (nomesReceitas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma receita cadastrada.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            for (String nome : nomesReceitas) {
                listaModelo.addElement(nome);
            }
        }
    }

    private void consultarReceita() {
        String nomeConsulta = txtfieldDesejaCons.getText().trim();

        if (nomeConsulta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um nome para a consulta!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Receita receitaEncontrada = null;
        
        try {
            receitaEncontrada = new ReceitaController().buscarReceitaPorNome(nomeConsulta);
        } catch (NomeException | NivelDifException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro na busca da receita: " + e.getMessage());
        }

        if (receitaEncontrada != null) {
            exibirDetalhesNaTabela(receitaEncontrada);
        } else {
            JOptionPane.showMessageDialog(this, "Receita não encontrada!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exibirDetalhesNaTabela(Receita receita) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"Campo", "Valor"});

        modelo.addRow(new Object[]{"Nome", receita.getNome()});
        modelo.addRow(new Object[]{"Tempo de Preparo", receita.getTempPreparo() + " minutos"});
        modelo.addRow(new Object[]{"Nível de Dificuldade", receita.getNivelDific()});
        modelo.addRow(new Object[]{"Calorias", receita.getValorKcal()});
        modelo.addRow(new Object[]{"Porções", receita.getPorcoes()});

        if (receita instanceof Lanche l) {
            modelo.addRow(new Object[]{"Tipo de Lanche", l.getTipoLanche()});
            modelo.addRow(new Object[]{"Temperatura", l.getTemperatura()});
        } else if (receita instanceof Refeicao r) {
            modelo.addRow(new Object[]{"Acompanhamento", r.getAcompanhamento()});
            modelo.addRow(new Object[]{"Bebida", r.getBebida()});
        } else if (receita instanceof Sobremesa s) {
            modelo.addRow(new Object[]{"Categoria", s.getCategoria()});
            modelo.addRow(new Object[]{"Nível de Doçura", s.getNivelDoce()});
        }
        
        if (!receita.getIngredientes().isEmpty()) {
            for (Ingrediente ing : receita.getIngredientes()) {
                modelo.addRow(new Object[]{"Ingrediente", ing.getNome() + ": " + ing.getQuantidade() + " " + ing.getUnidMedida()});
            }
        } else {
            modelo.addRow(new Object[]{"Ingredientes", "Nenhum cadastrado"});
        }

        jTableReceita.setModel(modelo); 
    }

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Saida", JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btSair;
    private javax.swing.JList<String> jListReceitas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableReceita;
    private javax.swing.JLabel labelConsulta;
    private javax.swing.JLabel labelDesejaCons;
    private javax.swing.JTextField txtfieldDesejaCons;
    // End of variables declaration//GEN-END:variables
}
