package view;

import exceptions.NivelDifException;
import exceptions.NomeException;
import model.Ingrediente;
import controller.LancheController;
import model.Lanche;
import javax.swing.JOptionPane;


public class FormLanche extends javax.swing.JFrame {
    private static FormLanche formLanche;
      
    private FormLanche() {
        initComponents();
        
    }

    public static FormLanche getFormLanche(){
        if(formLanche == null){
            formLanche = new FormLanche();
        }
        return formLanche;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelTitulo = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        txfieldNome = new javax.swing.JTextField();
        labelTempPrep = new javax.swing.JLabel();
        txfieldTempPrep = new javax.swing.JTextField();
        labelNivDif = new javax.swing.JLabel();
        txfieldNivDif = new javax.swing.JTextField();
        labelKcal = new javax.swing.JLabel();
        txfieldKcal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btAdicionarLanche = new javax.swing.JButton();
        labelTipoLanche = new javax.swing.JLabel();
        labelTemperatura = new javax.swing.JLabel();
        txfieldTipoLanche = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        txfieldTemperatura = new javax.swing.JTextField();
        labelPorcoes = new javax.swing.JLabel();
        txfieldPorcoes = new javax.swing.JTextField();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        labelTitulo.setText("Adicionar Lanche");

        labelNome.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelNome.setText("Nome:");

        txfieldNome.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txfieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfieldNomeActionPerformed(evt);
            }
        });

        labelTempPrep.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelTempPrep.setText("Tempo de preparo (min):");

        txfieldTempPrep.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        labelNivDif.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelNivDif.setText("Nível de Dificuldade (1 a 5):");

        labelKcal.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelKcal.setText("Valor Kcal:");

        txfieldKcal.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txfieldKcal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txfieldKcal.setMinimumSize(new java.awt.Dimension(90, 24));

        btAdicionarLanche.setText("Adicionar Lanche");
        btAdicionarLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarLancheActionPerformed(evt);
            }
        });

        labelTipoLanche.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelTipoLanche.setText("Tipo do lanche:");

        labelTemperatura.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelTemperatura.setText("Temperatura");

        txfieldTipoLanche.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txfieldTipoLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfieldTipoLancheActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        txfieldTemperatura.setPreferredSize(new java.awt.Dimension(80, 23));
        txfieldTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfieldTemperaturaActionPerformed(evt);
            }
        });

        labelPorcoes.setText("Porções:");

        txfieldPorcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfieldPorcoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAdicionarLanche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTipoLanche)
                                    .addComponent(labelTemperatura)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelPorcoes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfieldPorcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfieldTipoLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(txfieldTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelTempPrep)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfieldTempPrep))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelNivDif)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfieldNivDif))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelKcal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfieldKcal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(txfieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTempPrep)
                    .addComponent(txfieldTempPrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNivDif)
                    .addComponent(txfieldNivDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKcal)
                    .addComponent(txfieldKcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPorcoes)
                    .addComponent(txfieldPorcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoLanche)
                    .addComponent(txfieldTipoLanche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTemperatura)
                    .addComponent(txfieldTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionarLanche)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>                        

    private void txfieldNomeActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btAdicionarLancheActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        cadastrarLanche();
    }                                                 

    private void txfieldTipoLancheActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {                                         
        limpar();
    }                                        

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {                                       
        sair();
    }                                      

    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
    }                                    

    private void txfieldTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void txfieldPorcoesActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

        
    private void cadastrarLanche() {
        Lanche lanche = new Lanche();

        try {
            lanche.setNome(txfieldNome.getText());
        } catch (NomeException ne) {
            JOptionPane.showMessageDialog(this, "Nome inválido! O nome deve ter pelo menos 3 caracteres.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNome.setText("");
            txfieldNome.requestFocus();
            return;
        }  

        try {
            lanche.setNivelDific(Integer.parseInt(txfieldNivDif.getText()));
        } catch (NivelDifException nde) {
            JOptionPane.showMessageDialog(this, "Nível de dificuldade deve estar entre 1 e 5.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNivDif.setText("");
            txfieldNivDif.requestFocus();
            return;
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Entrada inválida! Digite um número inteiro.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNivDif.setText("");
            txfieldNivDif.requestFocus();
            return;
        }

        try {
            lanche.setValorKcal(Integer.parseInt(txfieldKcal.getText()));
            lanche.setTempPreparo(Integer.parseInt(txfieldTempPrep.getText()));
            lanche.setPorcoes(Integer.parseInt(txfieldPorcoes.getText()));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Erro: Certifique-se de preencher os campos corretamente com números!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        lanche.setTipoLanche(txfieldTipoLanche.getText());
        lanche.setTemperatura(txfieldTemperatura.getText());

        FormIngrediente formIngrediente = FormIngrediente.getFormIngrediente();
        formIngrediente.setReceitaAtual(lanche);  
        FormIngrediente.getFormIngrediente().setVisible(true);
        
        LancheController ct = new LancheController();
        ct.cadastrar(lanche);

        JOptionPane.showMessageDialog(this, "Lanche cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        limpar();
        this.dispose();
    }

    public void limpar(){
        txfieldKcal.setText("");
        txfieldNivDif.setText("");
        txfieldNome.setText("");
        txfieldTempPrep.setText("");
        txfieldTipoLanche.setText("");
        txfieldNome.requestFocus();
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Saida", JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLanche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btAdicionarLanche;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelKcal;
    private javax.swing.JLabel labelNivDif;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPorcoes;
    private javax.swing.JLabel labelTempPrep;
    private javax.swing.JLabel labelTemperatura;
    private javax.swing.JLabel labelTipoLanche;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField txfieldKcal;
    private javax.swing.JTextField txfieldNivDif;
    private javax.swing.JTextField txfieldNome;
    private javax.swing.JTextField txfieldPorcoes;
    private javax.swing.JTextField txfieldTempPrep;
    private javax.swing.JTextField txfieldTemperatura;
    private javax.swing.JTextField txfieldTipoLanche;
    // End of variables declaration                   
}
