package view;

//Netbeans IDE23
//Isadora Costa Baía - RA2614685
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import model.Ingrediente;
import model.Refeicao;
import javax.swing.JOptionPane;

/**
 *
 * @author isadorabaia
 */
public class FormRefeicao extends javax.swing.JFrame {
    private Refeicao refeicao;
    private Ingrediente ingrediente;
    private static FormRefeicao cadRefeicao;
      
    /**
     * Creates new form CadLanche
     */
    private FormRefeicao() {
        initComponents();
    }

    //método Singleton
    public static FormRefeicao getCadRefeicao(){
        if(cadRefeicao == null){
            cadRefeicao = new FormRefeicao();
        }
        return cadRefeicao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelTitulo = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        txfieldNome = new javax.swing.JTextField();
        labelTempPrep = new javax.swing.JLabel();
        txfieldTempPrep = new javax.swing.JTextField();
        labelNivDif = new javax.swing.JLabel();
        txfieldNivDif = new javax.swing.JTextField();
        labelKcal = new javax.swing.JLabel();
        txfieldKcal = new javax.swing.JTextField();
        btAdicionarRefeicao = new javax.swing.JButton();
        labelNPorcoes = new javax.swing.JLabel();
        labelAcomp = new javax.swing.JLabel();
        txfieldNPorcoes = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        txfieldAcomp = new javax.swing.JTextField();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        labelTitulo.setText("Adicionar Refeição");

        labelNome.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelNome.setText("Nome:");

        txfieldNome.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txfieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfieldNomeActionPerformed(evt);
            }
        });

        labelTempPrep.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelTempPrep.setText("Tempo de preparo (min):");

        txfieldTempPrep.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        labelNivDif.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelNivDif.setText("Nível de Dificuldade (1 a 5):");

        labelKcal.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelKcal.setText("Valor Kcal:");

        txfieldKcal.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        btAdicionarRefeicao.setText("Adicionar Refeicao");
        btAdicionarRefeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarRefeicaoActionPerformed(evt);
            }
        });

        labelNPorcoes.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelNPorcoes.setText("N de Porções:");

        labelAcomp.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelAcomp.setText("Tem acompanhamento? (1-Sim, 2-Não):");

        txfieldNPorcoes.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txfieldNPorcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfieldNPorcoesActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btAdicionarRefeicao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSair))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelKcal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfieldKcal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelNPorcoes)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfieldNPorcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(labelNivDif)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txfieldNivDif))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(labelTempPrep)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txfieldTempPrep))
                                        .addComponent(labelAcomp))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfieldAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(txfieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTempPrep)
                    .addComponent(txfieldTempPrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNivDif)
                    .addComponent(txfieldNivDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKcal)
                    .addComponent(txfieldKcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNPorcoes)
                    .addComponent(txfieldNPorcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAcomp)
                    .addComponent(txfieldAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionarRefeicao)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfieldNomeActionPerformed

    private void btAdicionarRefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarRefeicaoActionPerformed
        cadastrarRefeicao();
    }//GEN-LAST:event_btAdicionarRefeicaoActionPerformed

    private void txfieldNPorcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfieldNPorcoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfieldNPorcoesActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void cadastrarRefeicao() {
        Refeicao refeicao = new Refeicao();

        try {
            refeicao.setNome(txfieldNome.getText());
        } catch (NomeException ne) {
            JOptionPane.showMessageDialog(this, "Nome inválido! O nome deve ter pelo menos 3 caracteres.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNome.setText("");
            txfieldNome.requestFocus();
            return;
        }  

        try {
            refeicao.setNivelDific(Integer.parseInt(txfieldNivDif.getText()));
        } catch (NivelDifException nde) {
            JOptionPane.showMessageDialog(this, "Nível de dificuldade deve estar entre 1 e 5.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNivDif.setText("");
            txfieldNivDif.requestFocus();
            return;
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Entrada inválida! Digite um número inteiro.", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldNivDif.setText("");
            txfieldNivDif.requestFocus();
            return;
        }

        try {
            refeicao.setValorKcal(Integer.parseInt(txfieldKcal.getText()));
            refeicao.setTempPreparo(Integer.parseInt(txfieldTempPrep.getText()));
            refeicao.setPorcoes(Integer.parseInt(txfieldNPorcoes.getText()));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Erro: Certifique-se de preencher os campos corretamente com números!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            int acompanhamento = Integer.parseInt(txfieldAcomp.getText().trim());

            if (acompanhamento == 1 || acompanhamento == 2) {
                refeicao.setTemAcomp(acompanhamento);
            } else {
                JOptionPane.showMessageDialog(this, "Entrada inválida! Digite 1 para Sim e 2 para Não.", "Erro", JOptionPane.ERROR_MESSAGE);
                txfieldAcomp.setText("");
                txfieldAcomp.requestFocus();
                return;
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Erro: Digite um número válido (1 para Sim, 2 para Não).", "Erro", JOptionPane.ERROR_MESSAGE);
            txfieldAcomp.setText("");
            txfieldAcomp.requestFocus();
            return;
        }

        FormIngrediente formIngrediente = FormIngrediente.getCadIngrediente();
        formIngrediente.setReceitaAtual(refeicao);  

        FormIngrediente.getCadIngrediente().setVisible(true);
          
        BdReceitas.getBdReceitas().adicionarReceita(refeicao);

        JOptionPane.showMessageDialog(this, "Refeicao cadastrada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        limpar();
        this.dispose();
    }

    public void limpar(){
        txfieldKcal.setText("");
        txfieldNivDif.setText("");
        txfieldNome.setText("");
        txfieldTempPrep.setText("");
        txfieldNPorcoes.setText("");
        txfieldAcomp.setText("");
        txfieldNome.requestFocus();
    }
      
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Saida", JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRefeicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarRefeicao;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelAcomp;
    private javax.swing.JLabel labelKcal;
    private javax.swing.JLabel labelNPorcoes;
    private javax.swing.JLabel labelNivDif;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTempPrep;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField txfieldAcomp;
    private javax.swing.JTextField txfieldKcal;
    private javax.swing.JTextField txfieldNPorcoes;
    private javax.swing.JTextField txfieldNivDif;
    private javax.swing.JTextField txfieldNome;
    private javax.swing.JTextField txfieldTempPrep;
    // End of variables declaration//GEN-END:variables
}
