package view;

import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        labelBemVindo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        itemAdicionarLanche = new javax.swing.JMenuItem();
        itemAdicionarRefeicao = new javax.swing.JMenuItem();
        itemAdicionarSobremesa = new javax.swing.JMenuItem();
        itemConsultar = new javax.swing.JMenuItem();
        itemExcluir = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelBemVindo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        labelBemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBemVindo.setText("Menu Principal");

        menuPrincipal.setText("Menu");

        jMenu1.setText("Adicionar Receita");

        itemAdicionarLanche.setText("Adicionar Lanche");
        itemAdicionarLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAdicionarLancheActionPerformed(evt);
            }
        });
        jMenu1.add(itemAdicionarLanche);

        itemAdicionarRefeicao.setText("Adicionar Refeicao");
        itemAdicionarRefeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAdicionarRefeicaoActionPerformed(evt);
            }
        });
        jMenu1.add(itemAdicionarRefeicao);

        itemAdicionarSobremesa.setText("Adicionar Sobremesa");
        itemAdicionarSobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAdicionarSobremesaActionPerformed(evt);
            }
        });
        jMenu1.add(itemAdicionarSobremesa);

        menuPrincipal.add(jMenu1);

        itemConsultar.setText("Consultar Receita");
        itemConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarActionPerformed(evt);
            }
        });
        menuPrincipal.add(itemConsultar);

        itemExcluir.setText("Excluir Receita");
        itemExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExcluirActionPerformed(evt);
            }
        });
        menuPrincipal.add(itemExcluir);

        menuBar.add(menuPrincipal);

        menuSair.setText("Sair");

        itemSair.setText("Saída");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuSair.add(itemSair);

        menuBar.add(menuSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(labelBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(labelBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAdicionarLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAdicionarLancheActionPerformed
        FormLanche.getFormLanche().setVisible(true);
    }//GEN-LAST:event_itemAdicionarLancheActionPerformed

    private void itemConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarActionPerformed
        FormConsultar.getFormConsulta().setVisible(true);
    }//GEN-LAST:event_itemConsultarActionPerformed

    private void itemAdicionarRefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAdicionarRefeicaoActionPerformed
        FormRefeicao.getFormRefeicao().setVisible(true);
    }//GEN-LAST:event_itemAdicionarRefeicaoActionPerformed

    private void itemAdicionarSobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAdicionarSobremesaActionPerformed
        FormSobremesa.getFormSobremesa().setVisible(true);
    }//GEN-LAST:event_itemAdicionarSobremesaActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        sair();
    }//GEN-LAST:event_itemSairActionPerformed

    private void itemExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExcluirActionPerformed
        FormExcluir.getFormExcluir().setVisible(true);
    }//GEN-LAST:event_itemExcluirActionPerformed
    
  
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Saida", JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAdicionarLanche;
    private javax.swing.JMenuItem itemAdicionarRefeicao;
    private javax.swing.JMenuItem itemAdicionarSobremesa;
    private javax.swing.JMenuItem itemConsultar;
    private javax.swing.JMenuItem itemExcluir;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel labelBemVindo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
